/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'matthias' at '3/13/16 7:18 PM' with Gradle 2.11
 *
 * @author matthias, @date 3/13/16 7:18 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
