/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'matthias' at '3/13/16 7:18 PM' with Gradle 2.11
 *
 * @author matthias, @date 3/13/16 7:18 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
